/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Attributes:     success: [TODO:attribute]     msg: [TODO:attribute]     code:         # 0 success         # 1 invalid time str format         # 2 token lost         # 3 token expired         # 4 Invalid outcome value which is not negative         # 5 Invliad outcome value         # 6 Unkown Error
 *
 * @param success 
 * @param msg 
 * @param code 
 */
@Serializable

data class AddOutcomeResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "code")
    val code: kotlin.Int

) {


}

