/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token 
 * @param accountBookId 
 * @param startTime 
 * @param endTime 
 * @param note 
 */
@Serializable

data class BookDetailRequest (

    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "account_book_id")
    val accountBookId: kotlin.Int,

    @SerialName(value = "start_time")
    val startTime: kotlin.String,

    @SerialName(value = "end_time")
    val endTime: kotlin.String,

    @SerialName(value = "note")
    val note: kotlin.String

) {


}

