/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param nameOrEmail 
 * @param oldPwdHash 
 * @param newPwdHash 
 */
@Serializable

data class ChangePasswordRequest (

    @SerialName(value = "name_or_email")
    val nameOrEmail: kotlin.String,

    @SerialName(value = "old_pwd_hash")
    val oldPwdHash: kotlin.String,

    @SerialName(value = "new_pwd_hash")
    val newPwdHash: kotlin.String

) {


}

