/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.InterfacesApi
import org.openapitools.client.models.AddIncomeRequest
import org.openapitools.client.models.AddIncomeResponse
import org.openapitools.client.models.AddOutcomeRequest
import org.openapitools.client.models.AddOutcomeResponse
import org.openapitools.client.models.BookDetailRequest
import org.openapitools.client.models.BookDetailResponse
import org.openapitools.client.models.ChangePasswordRequest
import org.openapitools.client.models.ChangePasswordResponse
import org.openapitools.client.models.CreateAccountBookRequest
import org.openapitools.client.models.CreateAccountBookResponse
import org.openapitools.client.models.GetUserProfileRequest
import org.openapitools.client.models.GetUserProfileResponse
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.ListBookRequest
import org.openapitools.client.models.ListBookResponse
import org.openapitools.client.models.LoginRequest
import org.openapitools.client.models.LoginResponse
import org.openapitools.client.models.LogoutRequest
import org.openapitools.client.models.LogoutResponse
import org.openapitools.client.models.RefreshTokenRequest
import org.openapitools.client.models.RefreshTokenResponse
import org.openapitools.client.models.RegisterRequest
import org.openapitools.client.models.RegisterResponse
import org.openapitools.client.models.RemoveBookRequest
import org.openapitools.client.models.RemoveBookResponse

class InterfacesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InterfacesApi
        //val apiInstance = InterfacesApi()

        // to test addIncomeCoinVerseBookTransactionsAddIncomePost
        should("test addIncomeCoinVerseBookTransactionsAddIncomePost") {
            // uncomment below to test addIncomeCoinVerseBookTransactionsAddIncomePost
            //val addIncomeRequest : AddIncomeRequest =  // AddIncomeRequest | 
            //val result : AddIncomeResponse = apiInstance.addIncomeCoinVerseBookTransactionsAddIncomePost(addIncomeRequest)
            //result shouldBe ("TODO")
        }

        // to test addOutcomeCoinVerseBookTransactionsAddOutcomePost
        should("test addOutcomeCoinVerseBookTransactionsAddOutcomePost") {
            // uncomment below to test addOutcomeCoinVerseBookTransactionsAddOutcomePost
            //val addOutcomeRequest : AddOutcomeRequest =  // AddOutcomeRequest | 
            //val result : AddOutcomeResponse = apiInstance.addOutcomeCoinVerseBookTransactionsAddOutcomePost(addOutcomeRequest)
            //result shouldBe ("TODO")
        }

        // to test changePasswordCoinVerseUsersMeChangePasswordPut
        should("test changePasswordCoinVerseUsersMeChangePasswordPut") {
            // uncomment below to test changePasswordCoinVerseUsersMeChangePasswordPut
            //val changePasswordRequest : ChangePasswordRequest =  // ChangePasswordRequest | 
            //val result : ChangePasswordResponse = apiInstance.changePasswordCoinVerseUsersMeChangePasswordPut(changePasswordRequest)
            //result shouldBe ("TODO")
        }

        // to test createAccBookCoinVerseCreateBookPost
        should("test createAccBookCoinVerseCreateBookPost") {
            // uncomment below to test createAccBookCoinVerseCreateBookPost
            //val createAccountBookRequest : CreateAccountBookRequest =  // CreateAccountBookRequest | 
            //val result : CreateAccountBookResponse = apiInstance.createAccBookCoinVerseCreateBookPost(createAccountBookRequest)
            //result shouldBe ("TODO")
        }

        // to test getBookDetailCoinVerseBooksDetailPost
        should("test getBookDetailCoinVerseBooksDetailPost") {
            // uncomment below to test getBookDetailCoinVerseBooksDetailPost
            //val bookDetailRequest : BookDetailRequest =  // BookDetailRequest | 
            //val result : BookDetailResponse = apiInstance.getBookDetailCoinVerseBooksDetailPost(bookDetailRequest)
            //result shouldBe ("TODO")
        }

        // to test getProfileCoinVerseUsersMePost
        should("test getProfileCoinVerseUsersMePost") {
            // uncomment below to test getProfileCoinVerseUsersMePost
            //val getUserProfileRequest : GetUserProfileRequest =  // GetUserProfileRequest | 
            //val result : GetUserProfileResponse = apiInstance.getProfileCoinVerseUsersMePost(getUserProfileRequest)
            //result shouldBe ("TODO")
        }

        // to test listAccBookCoinVerseListBooksPut
        should("test listAccBookCoinVerseListBooksPut") {
            // uncomment below to test listAccBookCoinVerseListBooksPut
            //val listBookRequest : ListBookRequest =  // ListBookRequest | 
            //val result : ListBookResponse = apiInstance.listAccBookCoinVerseListBooksPut(listBookRequest)
            //result shouldBe ("TODO")
        }

        // to test loginCoinVerseLoginPost
        should("test loginCoinVerseLoginPost") {
            // uncomment below to test loginCoinVerseLoginPost
            //val loginRequest : LoginRequest =  // LoginRequest | 
            //val result : LoginResponse = apiInstance.loginCoinVerseLoginPost(loginRequest)
            //result shouldBe ("TODO")
        }

        // to test logoutCoinVerseLogoutPost
        should("test logoutCoinVerseLogoutPost") {
            // uncomment below to test logoutCoinVerseLogoutPost
            //val logoutRequest : LogoutRequest =  // LogoutRequest | 
            //val result : LogoutResponse = apiInstance.logoutCoinVerseLogoutPost(logoutRequest)
            //result shouldBe ("TODO")
        }

        // to test refreshTokenCoinVerseRefreshTokenPost
        should("test refreshTokenCoinVerseRefreshTokenPost") {
            // uncomment below to test refreshTokenCoinVerseRefreshTokenPost
            //val refreshTokenRequest : RefreshTokenRequest =  // RefreshTokenRequest | 
            //val result : RefreshTokenResponse = apiInstance.refreshTokenCoinVerseRefreshTokenPost(refreshTokenRequest)
            //result shouldBe ("TODO")
        }

        // to test registerUserCoinVerseRegisterPost
        should("test registerUserCoinVerseRegisterPost") {
            // uncomment below to test registerUserCoinVerseRegisterPost
            //val registerRequest : RegisterRequest =  // RegisterRequest | 
            //val result : RegisterResponse = apiInstance.registerUserCoinVerseRegisterPost(registerRequest)
            //result shouldBe ("TODO")
        }

        // to test removeBookCoinVerseBooksRemoveBookPost
        should("test removeBookCoinVerseBooksRemoveBookPost") {
            // uncomment below to test removeBookCoinVerseBooksRemoveBookPost
            //val removeBookRequest : RemoveBookRequest =  // RemoveBookRequest | 
            //val result : RemoveBookResponse = apiInstance.removeBookCoinVerseBooksRemoveBookPost(removeBookRequest)
            //result shouldBe ("TODO")
        }

    }
}
