/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AddIncomeRequest

class AddIncomeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddIncomeRequest
        //val modelInstance = AddIncomeRequest()

        // to test the property `token`
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `accountBookId`
        should("test accountBookId") {
            // uncomment below to test the property
            //modelInstance.accountBookId shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `time`
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

        // to test the property `note`
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

        // to test the property `incomeIdx`
        should("test incomeIdx") {
            // uncomment below to test the property
            //modelInstance.incomeIdx shouldBe ("TODO")
        }

    }
}
