/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ChangePasswordRequest

class ChangePasswordRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChangePasswordRequest
        //val modelInstance = ChangePasswordRequest()

        // to test the property `nameOrEmail`
        should("test nameOrEmail") {
            // uncomment below to test the property
            //modelInstance.nameOrEmail shouldBe ("TODO")
        }

        // to test the property `oldPwdHash`
        should("test oldPwdHash") {
            // uncomment below to test the property
            //modelInstance.oldPwdHash shouldBe ("TODO")
        }

        // to test the property `newPwdHash`
        should("test newPwdHash") {
            // uncomment below to test the property
            //modelInstance.newPwdHash shouldBe ("TODO")
        }

    }
}
