/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CreateAccountBookRequest

class CreateAccountBookRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateAccountBookRequest
        //val modelInstance = CreateAccountBookRequest()

        // to test the property `token`
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `bookName`
        should("test bookName") {
            // uncomment below to test the property
            //modelInstance.bookName shouldBe ("TODO")
        }

    }
}
