/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.LoginRequest

class LoginRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoginRequest
        //val modelInstance = LoginRequest()

        // to test the property `nameOrEmail`
        should("test nameOrEmail") {
            // uncomment below to test the property
            //modelInstance.nameOrEmail shouldBe ("TODO")
        }

        // to test the property `pwdHash`
        should("test pwdHash") {
            // uncomment below to test the property
            //modelInstance.pwdHash shouldBe ("TODO")
        }

        // to test the property `maintainOnline`
        should("test maintainOnline") {
            // uncomment below to test the property
            //modelInstance.maintainOnline shouldBe ("TODO")
        }

    }
}
