/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RefreshTokenRequest

class RefreshTokenRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RefreshTokenRequest
        //val modelInstance = RefreshTokenRequest()

        // to test the property `oldToken`
        should("test oldToken") {
            // uncomment below to test the property
            //modelInstance.oldToken shouldBe ("TODO")
        }

    }
}
