/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RefreshTokenResponse

class RefreshTokenResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RefreshTokenResponse
        //val modelInstance = RefreshTokenResponse()

        // to test the property `sucess`
        should("test sucess") {
            // uncomment below to test the property
            //modelInstance.sucess shouldBe ("TODO")
        }

        // to test the property `expired`
        should("test expired") {
            // uncomment below to test the property
            //modelInstance.expired shouldBe ("TODO")
        }

        // to test the property `msg`
        should("test msg") {
            // uncomment below to test the property
            //modelInstance.msg shouldBe ("TODO")
        }

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `tokenType`
        should("test tokenType") {
            // uncomment below to test the property
            //modelInstance.tokenType shouldBe ("TODO")
        }

    }
}
