/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Attributes:     success: [TODO:attribute]     msg: [TODO:attribute]     code:         # 0 success         # 1 invalid time str format         # 2 requireInfo lost (useless         # 3 token lost         # 4 token expired         # 5 income type index invalid         # 6 unkown
 *
 * @param success 
 * @param msg 
 * @param code 
 */
@Serializable

data class AddIncomeResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "code")
    val code: kotlin.Int

) {


}

