/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token 
 * @param accountBookId 
 * @param amount 
 * @param time 
 * @param note 
 * @param outcomeIdx 
 */
@Serializable

data class AddOutcomeRequest (

    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "account_book_id")
    val accountBookId: kotlin.Int,

    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    @SerialName(value = "time")
    val time: kotlin.String,

    @SerialName(value = "note")
    val note: kotlin.String,

    @SerialName(value = "outcome_idx")
    val outcomeIdx: kotlin.Int

) {


}

