/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Attributes:     success: status     code:         # 0 success         # 1 invlaid start_time or end time         # 2 token lost         # 3 token expired         # 4 unkown     transactions: [TODO:attribute]
 *
 * @param success 
 * @param msg 
 * @param code 
 * @param transactions 
 */
@Serializable

data class BookDetailResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "code")
    val code: kotlin.Int,

    @SerialName(value = "transactions")
    val transactions: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.Any>>>

) {


}

