/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param nameOrEmail 
 * @param pwdHash 
 * @param maintainOnline 
 */
@Serializable

data class LoginRequest (

    @SerialName(value = "name_or_email")
    val nameOrEmail: kotlin.String,

    @SerialName(value = "pwd_hash")
    val pwdHash: kotlin.String,

    @SerialName(value = "maintain_online")
    val maintainOnline: kotlin.Boolean

) {


}

