/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sucess 
 * @param expired 
 * @param msg 
 * @param accessToken 
 * @param tokenType 
 */
@Serializable

data class RefreshTokenResponse (

    @SerialName(value = "sucess")
    val sucess: kotlin.Boolean,

    @SerialName(value = "expired")
    val expired: kotlin.Boolean,

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "token_type")
    val tokenType: kotlin.String? = "bearer"

) {


}

