/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Attributes:     success: the ops status     code:         # 0 success         # 1 token lost         # 2 token expired     msg: info ops
 *
 * @param success 
 * @param code 
 * @param msg 
 */
@Serializable

data class RemoveBookResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "code")
    val code: kotlin.Int,

    @SerialName(value = "msg")
    val msg: kotlin.String

) {


}

